import { getPageBySlug, Page } from '@/services/pageService';
import { notFound } from 'next/navigation';

type Props = {
  params: {
    slug: string;
  };
};

export async function generateMetadata({ params }: Props) {
    const page = await getPageBySlug(params.slug);
    if (!page) {
        return {
            title: 'Sayfa Bulunamadı',
        }
    }
    return {
        title: `${page.title} | Bilge Yıldız Koleji`,
    }
}

export default async function DynamicPage({ params }: Props) {
  const page: Page | null = await getPageBySlug(params.slug);

  if (!page || !page.htmlContent) {
    notFound();
  }

  // The .prose class was overriding all the custom styles generated by the AI.
  // By removing it, the AI-generated HTML will now render with its intended
  // Tailwind classes for colors, shadows, lists, blockquotes, etc.
  return (
    <div className="pt-24 pb-16">
        <div dangerouslySetInnerHTML={{ __html: page.htmlContent }} />
    </div>
  );
}
