import { getPageBySlug, Page } from '@/services/pageService';
import { notFound } from 'next/navigation';

type Props = {
  params: {
    slug: string;
  };
};

export async function generateMetadata({ params }: Props) {
    const page = await getPageBySlug(params.slug);
    if (!page) {
        return {
            title: 'Sayfa Bulunamadı',
        }
    }
    return {
        title: `${page.title} | Bilge Yıldız Koleji`,
    }
}


export default async function DynamicPage({ params }: Props) {
  const page: Page | null = await getPageBySlug(params.slug);

  if (!page) {
    notFound();
  }

  return (
    <div className="bg-background pt-24 pb-16">
        <div className="container mx-auto px-4">
             {/* 
                We use dangerouslySetInnerHTML here because the content is generated as raw HTML by an AI. 
                In a real-world scenario with user-generated content, this would require sanitization 
                to prevent XSS attacks. However, since this content is generated by an admin-triggered,
                trusted AI process, we accept the risk for this feature.
            */}
            <div className="prose dark:prose-invert max-w-full" dangerouslySetInnerHTML={{ __html: page.htmlContent }} />
        </div>
    </div>
  );
}
