import { getPageBySlug, Page } from '@/services/pageService';
import { notFound } from 'next/navigation';

type Props = {
  params: {
    slug: string;
  };
};

export async function generateMetadata({ params }: Props) {
    const page = await getPageBySlug(params.slug);
    if (!page) {
        return {
            title: 'Sayfa Bulunamadı',
        }
    }
    return {
        title: `${page.title} | Bilge Yıldız Koleji`,
    }
}

export default async function DynamicPage({ params }: Props) {
  const page: Page | null = await getPageBySlug(params.slug);

  if (!page || !page.htmlContent) {
    notFound();
  }

  // Use a wrapper div with the 'prose' class to apply Tailwind's typography styles
  // to the HTML content generated by the AI. This ensures that elements like
  // <ul>, <blockquote>, etc., are styled beautifully and consistently.
  return (
    <div className="pt-24 pb-16">
        <div
            className="prose dark:prose-invert max-w-none"
            dangerouslySetInnerHTML={{ __html: page.htmlContent }}
        />
    </div>
  );
}
